// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLNganHangDeThi.Models;

#nullable disable

namespace QLNganHangDeThi.Migrations
{
    [DbContext(typeof(QuanLyDeThiContext))]
    partial class QuanLyDeThiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLNganHangDeThi.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DecentralizationId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId");

                    b.HasIndex("DecentralizationId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.CauHoi", b =>
                {
                    b.Property<int>("CauHoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CauHoiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CauHoiId"));

                    b.Property<string>("DapAn")
                        .HasColumnType("ntext");

                    b.Property<decimal?>("Diem")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<int?>("LoaiId")
                        .HasColumnType("int")
                        .HasColumnName("LoaiID");

                    b.Property<int?>("MonHocId")
                        .HasColumnType("int")
                        .HasColumnName("MonHocID");

                    b.Property<int?>("MucDoId")
                        .HasColumnType("int")
                        .HasColumnName("MucDoID");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.HasKey("CauHoiId")
                        .HasName("PK__CauHoi__1937D77B512A4B51");

                    b.HasIndex("LoaiId");

                    b.HasIndex("MonHocId");

                    b.HasIndex("MucDoId");

                    b.ToTable("CauHoi", (string)null);
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.CauHoiDeThi", b =>
                {
                    b.Property<int>("CauHoiDeThiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CauHoiDeThiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CauHoiDeThiId"));

                    b.Property<int?>("CauHoiId")
                        .HasColumnType("int")
                        .HasColumnName("CauHoiID");

                    b.Property<int?>("DeThiId")
                        .HasColumnType("int")
                        .HasColumnName("DeThiID");

                    b.Property<int?>("SoThuTu")
                        .HasColumnType("int");

                    b.HasKey("CauHoiDeThiId")
                        .HasName("PK__CauHoiDe__44B293AD7F57174C");

                    b.HasIndex("CauHoiId");

                    b.HasIndex("DeThiId");

                    b.ToTable("CauHoiDeThi", (string)null);
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.DeThi", b =>
                {
                    b.Property<int>("DeThiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DeThiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeThiId"));

                    b.Property<int?>("MauDeId")
                        .HasColumnType("int")
                        .HasColumnName("MauDeID");

                    b.Property<DateTime?>("NgayTaoDe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayThi")
                        .HasColumnType("date");

                    b.Property<string>("TenLop")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DeThiId")
                        .HasName("PK__DeThi__9F9645B076746A6B");

                    b.HasIndex("MauDeId");

                    b.ToTable("DeThi", (string)null);
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.Decentralization", b =>
                {
                    b.Property<int>("DecentralizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DecentralizationId"));

                    b.Property<string>("AuthorityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DecentralizationId");

                    b.ToTable("Decentralization");
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.HeDaoTao", b =>
                {
                    b.Property<int>("HeDtid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HeDTID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeDtid"));

                    b.Property<string>("TenHeDt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenHeDT");

                    b.HasKey("HeDtid")
                        .HasName("PK__HeDaoTao__0C0AE79436CCEB6B");

                    b.ToTable("HeDaoTao", (string)null);
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.LoaiCauHoi", b =>
                {
                    b.Property<int>("LoaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LoaiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiId"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LoaiId")
                        .HasName("PK__LoaiCauH__730A57591560A12A");

                    b.ToTable("LoaiCauHoi", (string)null);
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.MauDeThi", b =>
                {
                    b.Property<int>("MauDeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MauDeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MauDeId"));

                    b.Property<int?>("MonHocId")
                        .HasColumnType("int")
                        .HasColumnName("MonHocID");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ThoiGianLamBai")
                        .HasColumnType("int");

                    b.Property<int?>("TongSoCau")
                        .HasColumnType("int");

                    b.HasKey("MauDeId")
                        .HasName("PK__MauDeThi__487D9062835ED4D6");

                    b.HasIndex("MonHocId");

                    b.ToTable("MauDeThi", (string)null);
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.MonHoc", b =>
                {
                    b.Property<int>("MonHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MonHocID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonHocId"));

                    b.Property<int?>("HeDtid")
                        .HasColumnType("int")
                        .HasColumnName("HeDTID");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MonHocId")
                        .HasName("PK__MonHoc__4127737F245FAF89");

                    b.HasIndex("HeDtid");

                    b.ToTable("MonHoc", (string)null);
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.MucDoKho", b =>
                {
                    b.Property<int>("MucDoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MucDoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MucDoId"));

                    b.Property<string>("CapDo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("MoTa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MucDoId")
                        .HasName("PK__MucDoKho__3EAECAA4AB3028F9");

                    b.ToTable("MucDoKho", (string)null);
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.Account", b =>
                {
                    b.HasOne("QLNganHangDeThi.Models.Decentralization", "Decentralizations")
                        .WithMany("Accounts")
                        .HasForeignKey("DecentralizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decentralizations");
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.CauHoi", b =>
                {
                    b.HasOne("QLNganHangDeThi.Models.LoaiCauHoi", "Loai")
                        .WithMany("CauHois")
                        .HasForeignKey("LoaiId")
                        .HasConstraintName("FK__CauHoi__MaLoai__4222D4EF");

                    b.HasOne("QLNganHangDeThi.Models.MonHoc", "MonHoc")
                        .WithMany("CauHois")
                        .HasForeignKey("MonHocId");

                    b.HasOne("QLNganHangDeThi.Models.MucDoKho", "MucDo")
                        .WithMany("CauHois")
                        .HasForeignKey("MucDoId")
                        .HasConstraintName("FK__CauHoi__MaMucDo__412EB0B6");

                    b.Navigation("Loai");

                    b.Navigation("MonHoc");

                    b.Navigation("MucDo");
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.CauHoiDeThi", b =>
                {
                    b.HasOne("QLNganHangDeThi.Models.CauHoi", "CauHoi")
                        .WithMany("CauHoiDeThis")
                        .HasForeignKey("CauHoiId")
                        .HasConstraintName("FK__CauHoiDeT__MaCau__5165187F");

                    b.HasOne("QLNganHangDeThi.Models.DeThi", "DeThi")
                        .WithMany("CauHoiDeThis")
                        .HasForeignKey("DeThiId")
                        .HasConstraintName("FK__CauHoiDeT__MaDeT__5070F446");

                    b.Navigation("CauHoi");

                    b.Navigation("DeThi");
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.DeThi", b =>
                {
                    b.HasOne("QLNganHangDeThi.Models.MauDeThi", "MauDe")
                        .WithMany("DeThis")
                        .HasForeignKey("MauDeId")
                        .HasConstraintName("FK__DeThi__MaMauDe__4CA06362");

                    b.Navigation("MauDe");
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.MauDeThi", b =>
                {
                    b.HasOne("QLNganHangDeThi.Models.MonHoc", "MonHoc")
                        .WithMany("MauDeThis")
                        .HasForeignKey("MonHocId");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.MonHoc", b =>
                {
                    b.HasOne("QLNganHangDeThi.Models.HeDaoTao", "HeDt")
                        .WithMany("MonHocs")
                        .HasForeignKey("HeDtid");

                    b.Navigation("HeDt");
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.CauHoi", b =>
                {
                    b.Navigation("CauHoiDeThis");
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.DeThi", b =>
                {
                    b.Navigation("CauHoiDeThis");
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.Decentralization", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.HeDaoTao", b =>
                {
                    b.Navigation("MonHocs");
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.LoaiCauHoi", b =>
                {
                    b.Navigation("CauHois");
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.MauDeThi", b =>
                {
                    b.Navigation("DeThis");
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.MonHoc", b =>
                {
                    b.Navigation("CauHois");

                    b.Navigation("MauDeThis");
                });

            modelBuilder.Entity("QLNganHangDeThi.Models.MucDoKho", b =>
                {
                    b.Navigation("CauHois");
                });
#pragma warning restore 612, 618
        }
    }
}
